apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity: 
    storage: 100Mi
  volumeMode: Filesystem
  storageClassName: gp2
  #use storageClassName as standard if using Minikube cluster for your needs
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data
    type: DirectoryOrCreate
