# Multi-stage Dockerfile with Ubuntu
FROM ubuntu:latest AS build

# Install required packages
RUN apt-get update && \
    apt-get install -y openjdk-17-jdk maven

# Set working directory
WORKDIR /app

# Copy project files
COPY pom.xml ./
RUN mvn dependency:go-offline

COPY src ./src

# Build the application
RUN mvn clean package

# Final stage
#FROM ubuntu:latest

# Set working directory
WORKDIR /app

# Copy the built JAR from the build stage
COPY  /app/target/*.jar /app/app.jar

# Expose port
EXPOSE 8080

# Run the application
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
