apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-sample-app
      tier: backend
  template:
    metadata: 
      labels:
        app: k8s-sample-app
        tier: backend
    spec: 
      containers:
        - name: k8s-sample-app
          image: vijaysharmagcp0324/k8s-sample-app
        # - name: ...
        #   image: ...
